### ISSUE TITLE
User can view entries of all Pokémon

### ISSUE THREAD

**Issue by alicejeeunlee** [alicejeeunlee/pokedex#1]
## 💰 Motivation

User can view entries of all Pokémon

## 📐 Plan

Create a responsive homepage that shows all Generation 1 Pokémon. Display in order of Pokémon ID number.

## 🖼️ Wireframes

<img width="367" alt="Screen Shot 2022-08-02 at 3 38 38 PM" src="https://user-images.githubusercontent.com/106103291/182485458-03bfe40b-0548-4eab-b461-5442cae774da.png">
<img width="1104" alt="Screen Shot 2022-08-02 at 3 39 52 PM" src="https://user-images.githubusercontent.com/106103291/182485600-4c319ca6-2b00-4065-94c8-8eb4bbfd28ac.png">

## ✅ Task List

- [x] Write up HTML skeleton with dummy entries and apply CSS styling to match the wireframe.
- [x] Check that the entries look good on both mobile and desktop screens.
- [x] Get data from PokéAPI for first 151 Pokémon (generation 1).
- [x] Each Pokémon object should have ID, name properties with respective data from the API.
- [x] Define a function that takes a single Pokémon object and returns a DOM tree that matches one of the dummy entries in the HTML.
- [x] Append DOM creation to the page when the 'load' event is fired in function to get API data.
- [x] Remove the dummy HTML entry once all 151 Pokémon are successfully being appended to the DOM on page load.
- [x] Clean up all unnecessary styling. 
- [x] Test the app in a private browsing tab.
- [x] Fix all errors.
