### ISSUE TITLE
User can view details of each Pokémon

### ISSUE THREAD

**Issue by alicejeeunlee** [alicejeeunlee/pokedex#2]
## 💰 Motivation

Users will want to see information and stats on each Pokémon.

## 📐 Plan

When a user clicks on a pokémon from the homepage, display each Pokémon's information card. The user can click the horizontal bar icon to see stats or click the pokéball icon to toggle view back to information. The user can click on the down chevron icon to go back to the homepage. 

## 🖼️ Wireframes
![Screen Shot 2022-08-04 at 5 17 13 PM](https://user-images.githubusercontent.com/106103291/182976146-b0b9cb2f-acab-4be1-ac33-ec85f3dadf69.png)
![Screen Shot 2022-08-04 at 5 17 41 PM](https://user-images.githubusercontent.com/106103291/182976190-a378b4a6-7b64-4b81-b5e4-73f68dfe782f.png)

## ✅ Task List

- [x] Write up HTML skeleton for dummy detail view and apply CSS styling to match the wireframe.
- [x] Check that the entries look good on both mobile and desktop screens.
- [x] Add to data model to track current pokémon data.
- [x] Make network request function for info view to get necessary data.
- [x] Make another network request function to get text description.
- [x] Make function to render DOM tree.
- [x] Show DOM creation on page when user clicks on a pokémon.
- [x] Make an AddEventListener function to handle showing the homepage when down chevron icon is clicked.
- [x] Make AddEventListener function to handle showing stats view.
- [x] Clean up all unnecessary styling.
- [x] Test the app in a private browsing tab.
- [x] Fix all errors.
