### ISSUE TITLE
User can search for a specific Pokémon 

### ISSUE THREAD

**Issue by alicejeeunlee** [alicejeeunlee/pokedex#3]
## 💰 Motivation

Users will want to search for a specific Pokémon.

## 📐 Plan

Provide a search box that causes the entries list to only show matches.

## 🖼️ Wireframes
![Screen Shot 2022-08-05 at 11 53 24 AM](https://user-images.githubusercontent.com/106103291/183142780-5590c6f6-2111-4f92-b573-c53aaf39779a.png)
![Screen Shot 2022-08-05 at 11 54 30 AM](https://user-images.githubusercontent.com/106103291/183142938-cf6a5f91-4092-408d-858a-b693541316e6.png)

## ✅ Task List

- [x] Add search box in HTML and style CSS.
- [x] Make sure search box looks good on both mobile and desktop views.
- [x] Create search function
  - [x] Query select all entries
  - [x] Loop through nodeList to check if name property includes search input value
    - [x] If yes show entries
    - [x] Else hide entries
- [x] Clean up all unnecessary styling.
- [x] Test the app in a private browsing tab.
- [x] Fix all errors.
