### ISSUE TITLE
User can add favorite Pokémon

### ISSUE THREAD

**Issue by alicejeeunlee** [alicejeeunlee/pokedex#4]
## 💰 Motivation

User can add favorite Pokémon for easy access.

## 📐 Functionality

Create a favorites tab to store all Pokémon favorited by user. User can add to favorite by clicking on the heart icon in each Pokémon's info card. 

## 🖼️ Wireframes

![Screen Shot 2022-08-05 at 12 42 36 PM](https://user-images.githubusercontent.com/106103291/183149450-62221f36-4634-44ed-8e2d-766dace92d6f.png)
![Screen Shot 2022-08-05 at 12 43 32 PM](https://user-images.githubusercontent.com/106103291/183149563-21e5ff19-30f8-47a9-bf65-46310e068dbe.png)

## ✅ Task List

- [x] Add heart icon to HTML header and style CSS.
- [x] Ensure mobile and desktop views are responsive.
- [x] Update data model to have 'favorites' property and assign an empty array.
- [x] Update DOM card rendering function to create heart icon.
- [x] Add click event listener for heart icon in card rendering function.
  - [x] Change heart icon color to red.
  - [x] Add current pokémon object to data model favorite array.
- [x] Make function to stringify pokémon object and add to local storage and a function to parse JSON data.
- [x]  Make view swap function.
- [x] Add event listener on NAV heart icon.
  - [x] Change NAV heart icon color to red if view is favorites else black.
  - [x] Loop through array of favorites and call render entries function.
- [x] Render pokémon cards on favorites view.
- [x] If pokémon is in favorites, all pokémon card rendered should have red heart icon.
- [x] Pokémon should not be added if already in favorites.
- [x]  Clean up all unnecessary styling.
- [x] Test the app in a private browsing tab.
- [x] Fix all errors.
