### ISSUE TITLE
User can remove Pokémon from favorite list

### ISSUE THREAD

**Issue by alicejeeunlee** [alicejeeunlee/pokedex#5]
## 💰 Motivation

Users will want to remove Pokémon from favorite list if it is no longer their favorite.

## 📐 Plan

Users can click highlighted heart icon to remove from favorite list.

## 🖼️ Wireframes

<img width="1195" alt="Screen Shot 2022-08-11 at 9 56 32 AM" src="https://user-images.githubusercontent.com/106103291/184190986-c446e0a1-cfc1-4b2c-913f-911308d2459d.png">
<img width="1220" alt="Screen Shot 2022-08-11 at 9 57 06 AM" src="https://user-images.githubusercontent.com/106103291/184190997-280039aa-6b24-4f1c-b764-1805f68ca597.png">

## ✅ Task List

- [x] Add condition to heart icon click event handler function on pokémon card.
  - [x] If heart icon is red...
    - [x] Change heart icon to white.
    - [x] Remove from data.favorites.
  - [x] Else, add to data.favorites (feature 4).
- [x] Update back icon click event handler to show updated data.favorites (without removed pokémon entries).
- [x] If data.favorites is empty, show 'no pokémon in favorites' message.
- [x] Clean up all unnecessary styling.
- [x] Test the app in a private browsing tab.
- [x] Fix all errors.
